	define _PRN_TXT_LINE_PAUESE_ 40

printText1	ld hl, TEXT1_1
	ld de, #484a
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT1_2
	ld de, #4868 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT1_3
	ld de, #4889 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT1_4
	ld de, #48a7 
	jp PrintHuman

TEXT1_1	db "YOU HAS BEN", 0
TEXT1_2	db "WATCHING A DEMO", 0
TEXT1_3	db "WITH LONG, BUT", 0
TEXT1_4	db "NOT IMPORTANT NAME", 0

printText2	ld hl, TEXT2_1
	ld de, #484a
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT2_2
	ld de, #486a
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT2_3
	ld de, #488a
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT2_4
	ld de, #48a9 
	jp PrintHuman

TEXT2_1	db "ALL PICTURES", 0
TEXT2_2	db "AND VISUALS", 0
TEXT2_3	db "OF THIS DEMO", 0
TEXT2_4	db "GENERATED BY AI", 0

printText3	ld hl, TEXT3_1
	ld de, #4849 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT3_2
	ld de, #4867
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT3_3
	ld de, #4886 
	call PrintHuman

	ld hl, TEXT3_4
	ld de, #48a8 
	jp PrintHuman

TEXT3_1	db "ALL SOUNDTRACKS", 0
TEXT3_2	db "GENERATED BY AI TOO", 0
TEXT3_3	db "AND CONVERTED TO PT3", 0
TEXT3_4	db "BY AUTOSIRIL TOOL", 0

printText4	ld hl, TEXT4_1
	ld de, #4847 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT4_2
	ld de, #486b 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT4_3
	ld de, #4888 
	jp PrintHuman

TEXT4_1	db "HUGE PARTS OF CODE", 0
TEXT4_2	db "STOLEN FROM", 0
TEXT4_3	db "PREVIOUS RELEASES", 0

printText6	ld hl, TEXT6_1
	ld de, #4847 
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT6_2
	ld de, #4869
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT6_3
	ld de, #488b
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT6_4
	ld de, #48ad 
	jp PrintHuman

TEXT6_1	db "THIS DEMO HAS", 0
TEXT6_2	db "NO MESSAGE", 0
TEXT6_3	db "BUT...", 0
TEXT6_4	db "NEVERMIND", 0

printText5	ld hl, TEXT5_1
	ld de, #486c
	call PrintHuman
	ifndef _NOPAUSE_ : ld b, _PRN_TXT_LINE_PAUESE_ : halt : djnz $-1 : endif

	ld hl, TEXT5_2
	ld de, #488e
	jp PrintHuman

TEXT5_1	db "HAVE A", 0
TEXT5_2	db "NICE DAY", 0

; Print zero ended string with font 8х8; human speed;
; HL - Text pointer
; DE - Screen address
PrintHuman 	
1	ld a, (hl)
	or a : ret z
	push af
	ld a,"_"
	call PrintChar_8x8
	pop af
	dec de
	dec hl
	ifndef _NOPAUSE_
	dup 3
	halt
	edup
	endif
	call PrintChar_8x8
	jr 1b

; Print one char with ROM font
; DE - Screen memory address
; A  - char
PrintChar_8x8 	push hl, de, bc
	sub #1f
	ld hl, #3d00 - #08
	ld bc, #08
1	add hl, bc
	dec a
	jr nz, 1b

	dup 8 
	ld a,(hl) : ld (de),a		; normal
	inc d : inc l
	edup 

	pop bc, de, hl
	inc hl : inc de
	ret 
